# Please see the full example under examples/docker-compose.example.yml

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWD
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PASSWD
    ports:
      - $DB_PORT:3306

  valkey:
    image: valkey/valkey:8
    container_name: valkey
    restart: unless-stopped
    ports:
      - $REDIS_PORT:6379
    env_file:
      - .env
